name: build
on:
  push:

jobs:
  build:
    if: ${{ !startsWith(github.event.ref, 'refs/tags/') && contains(github.event.head_commit.message, '*') == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ubuntu-gradle-${{ hashFiles('*.gradle', 'gradle.properties') }}
          restore-keys: ubuntu-gradle-

      - name: Run Gradle build
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew :koishibot-monitor:shadowJar

      - name: Upload core artifact
        uses: actions/upload-artifact@v2
        with:
          name: core
          path: koishibot-core/build/libs/*.jar

      - name: Upload qq backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: qq-backend
          path: koishibot-qq-backend/build/libs/*.jar

      - name: Upload monitor artifact
        uses: actions/upload-artifact@v2
        with:
          name: monitor
          path: koishibot-monitor/build/libs/koishibot-monitor-all.jar

      - name: Upload signature artifact
        uses: actions/upload-artifact@v2
        with:
          name: signatures
          path: build/libs/*.txt